export const EDUCATION_TYPE = 'EDUCATION_TYPE'
export const YEAR_TYPE = 'YEAR_TYPE'
export const SEARCH_TYPE = 'SEARCH_TYPE'
export const SERIES_TYPE = 'SERIES_TYPE'
export const NUMBER_TYPE = 'NUMBER_TYPE'
export const SPECIAL_TYPE = 'SPECIAL_TYPE'
export const QUALIFY_TYPE = 'QUALIFY_TYPE'